### ISSUE TITLE
Demote some rare languages in the list of all Bibles

### ISSUE THREAD

**Issue by DavidIB** [tyndale/step#22]
We have a quick'n'dirty way of dividing the list of Bible languages into normal and rare - with the rarely used languages below the others so that people can find their own language more easily.  We do this by adding a backtick ( ` ) at the start of names of Bibles in obscure languages. 
Clearly this is not the best solution, but it is the one in place at present. 

The reason this is needed is that (for some reason) the list isn't in the order of the language name, but in the order of the name of the first Bible in that language. So, for example, "Latin" is under "V" for Vulgate. If you have time to change the order, that would be great. 

However, in the mean time, there are a few names that should have a backtick, and don't. 
The backtick should be added at  step.core.properties on the following: 
    
    AAK
    ABTMAPRIK
    KLV
    OMWA
    
For KLV you have to add a line. For this last one, change 
    
    app.versions.stepPrefix.OMW-A=`OMW-A
    
to 
    
    app.versions.stepPrefix.OMWA=`OMWA

**Comment by thetallweeks** [comment]
Is this the right place?
https://github.com/tyndale/step/blob/master/step-core/src/main/resources/step.core.properties

I don't see those anywhere in that file

**Comment by DavidIB** [comment]
YOu are right - there is no line for KLV or AAK or ABTMAPRIK so at about line 227 insert: 
app.versions.stepPrefix.AAK=`AAK
app.versions.stepPrefix.ABTMAPRIK=`ABTMAPRIK
app.versions.stepPrefix.KLV=`KLV

For the last one, the line exists but has to be changed (as in the prev comment)

As I understand it, these lines override the normal action which is to list each Bible by the name of its module. These overrides were origianlly intended to shorten long module names such as "Antoniades" to shorter ones such as "Ant". This long list at the end is a quick'n'dirty way to rename Bibles to place them at the end of the list. Not good programming, I'm afraid.
