### ISSUE TITLE
Update language interfaces from CrowdIn 

### ISSUE THREAD

**Issue by DavidIB** [tyndale/step#38]
Danish is now finished, and I think the Traditional Chinese (aka Cantonese) is much updated as well as others. 
Chris says: "There used to be an option to export all languages or some languages as property files. Then I'd just overwrite the ones in the step core resources folder. 
    Then test it out to check there are no issues. (Some phrases missing can cause runtime issues from memory, whereas others just revert back to another language)
Can't remember if someone needs to go in validate so phrases first though.
When I used to do it, I used to take a copy of ALL languages as it takes the same amount of time.
If the language didn't exist already I think there's a property is step-core.properties which is a list of available languages."

To do this you need to be a Manager at http://crowdin.net/project/step so join up then ask David IB to promote you.

**Comment by DavidIB** [comment]
I've marked this as "Help wanted" (ie an easy task) but admittedly I had a go some time ago and came across a problem I couldn't solve at the time. Unfortunately I didn't make a note.

**Comment by patricksptang** [comment]
Done
