### ISSUE TITLE
Link to the new Help pages

### ISSUE THREAD

**Issue by DavidIB** [tyndale/step#46]
New Help pages are now available  at [https://stepbibleguide.blogspot.com](https://stepbibleguide.blogspot.com)
They aren't completely finished, but they are MUCH better than what currently exists at https://stepweb.atlassian.net/wiki/display/SUG/Quick+overview

The only thing that needs doing, I think, is to swap these two addresses.

**Comment by patricksptang** [comment]
Added to the master branch in github.  Should be available in the next software update on www.stepbible.org
